# Generated by Django 4.1.1 on 2022-09-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anthology", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="post",
            new_name="anthology_p_publish_ca1060_idx",
            old_name="blog_post_publish_493ec4_idx",
        ),
    ]
