# Generated by Django 4.1.1 on 2022-09-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anthology", "0005_comment_comment_anthology_c_created_cc745e_idx"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="name",
            new_name="username",
        ),
    ]
